In [2]:
import torch
import numpy as np
import ddpgAgent
from soccer import SoccerEnviroment

"test"

'test'

In [3]:
MAX_EPISODES=200
MAX_STEP=200
LR_A=0.001
LR_C=0.002
GAMMA=0.01
MEMORY_CAPACITY=10000
BATCH_SIZE=32
TAU=0.01
RENDER=False
ENV = SoccerEnviroment()
agent=ddpgAgent.DDPGAgent(ENV, GAMMA,LR_A,LR_C,BATCH_SIZE,MEMORY_CAPACITY,TAU)
print(agent.actor)
print(agent.critic)

Actor(
  (fc1): Linear(in_features=3, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=5, bias=True)
)
Critic(
  (fc1): Linear(in_features=4, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=1, bias=True)
)


In [5]:
agent.actor.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 0.0064, -0.0290,  0.0733],
                      [ 0.0985,  0.2088,  0.0945],
                      [ 0.0993,  0.0017, -0.1231],
                      [ 0.0956,  0.0437,  0.0578],
                      [-0.1184,  0.0446,  0.0620],
                      [ 0.2518,  0.1238, -0.0369],
                      [-0.0938, -0.1853,  0.0831],
                      [-0.1074,  0.0324,  0.1371],
                      [ 0.0114, -0.1078, -0.1483],
                      [ 0.0119, -0.0735, -0.0598]])),
             ('fc1.bias',
              tensor([-0.5553,  0.3213,  0.0700, -0.3179, -0.1443,  0.0406,  0.5670,  0.2301,
                      -0.2124, -0.4473])),
             ('fc2.weight',
              tensor([[ 0.1348, -0.0911,  0.1304,  0.0477,  0.2119, -0.1946, -0.0046, -0.0619,
                        0.0309, -0.0824],
                      [-0.0423,  0.0804,  0.2125,  0.0815,  0.0593, -0.0606,  0.0136,  0.0933,
                        0.0176,  0.1

In [33]:
a.argmax(axis=0).detach()

tensor([0, 3, 2, 1, 0])

In [55]:
x=torch.tensor([[1,1,1],[3,3,3]])
y=torch.tensor([[2],[4]])
torch.cat((x,y),1)

tensor([[1, 1, 1, 2],
        [3, 3, 3, 4]])

In [60]:
p=torch.tensor([[0,0,0,10],
                [0,0,10,0],
                [0,10,0,0]])
p.argmax(axis=1)

tensor([3, 2, 1])

In [66]:
torch.tensor([0,0,1,0,0]).argmax(axis=-1)

tensor(2)